[package]
name = "atelier"
version = "0.0.2"
edition = "2021"
description = "A cognitive workshop for synthetic artificial intelligence"
authors = ["IteraLabs.ai <contact@iteralabs.ai>"]
license = "Apache-2.0"
repository = "https://github.com/iteralabs/atelier"

[lib]
name = "atelier"
crate-type = ["cdylib"]
path = "rust/lib.rs"

[dependencies]
pyo3 = "0.21.0"

[profile.release-lto]
inherits = "release"
lto = true

