[package]
name = "atelier"
version = "0.0.1"
edition = "2021"
description = "A cognitive workshop for synthetic artificial intelligence"
authors = ["IteraLabs.ai <contact@iteralabs.ai>"]
license = "Apache-2.0"
repository = "https://github.com/iteralabs/atelier"

[lib]
name = "atelier"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
