[workspace]
members = ["atelier-rs"]
resolver = "2"

[workspace.dependencies]
tch = { version = "^0.17" }
rand = "^0.8"
serde = { version = "^1.0" }
pyo3 = { version = "^0.22" }

[profile.release-lto]
inherits = "release"
lto = true