version: '3.10'
services:
  debian-mps:
    build:
      context: .
      dockerfile: docker/Dockerfile.debian-mps
    environment:
      - USE_CUDA=0
    ports:
      - "8080:80"
volumes:
  data_volume:
