version: '3.10'
services:
  fedora-mps:
    platform: linux/arm64
    build:
      context: .
      dockerfile: docker/mps/Dockerfile.fedora-mps
    ports:
      - "8081:80"
    tty: true
volumes:
  data_volume:
