site_name: Atelier
site_description: An Experimental, Rust-based, Python-wrapped, Workshop for ML 
repo_name: iteralabs/atelier
repo_url: https://github.com/iteralabs/atelier

nav: 
  - Welcome: index.md

theme:
  name: terminal

