site_name: Atelier
site_description: An Experimental, Rust-based, Python-wrapped, Workshop for ML 
repo_name: iteralabs/atelier
repo_url: https://github.com/iteralabs/atelier
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Iteralabs

nav: 
  - Welcome: index.md
  - User Guide: 
    - Installation: guide/installation.md
  - Changelog: changelog.md

theme:
  name: terminal
  features:
  - navigation.instant
  - navigation.tracking
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - content.action.edit
  - toc.integrate
  - toc.follow
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.footer

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - markdown_version_annotations
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_get"
  - mkdocs-version-annotations:
      version_added_title: 'new in **\1**'
      version_changed_title: 'changed in **\1**'
      version_removed_title: 'removed in **\1**'
  - include-markdown:
      preserve_includer_indent: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iteralabs
      name: Follow @iteralabs on GitHub
