site_name: Atelier
site_description: An Experimental, Rust-based, Python-wrapped, Workshop for ML 
repo_name: iteralabs/atelier
repo_url: https://github.com/iteralabs/atelier
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Iteralabs

nav: 
  - Welcome: index.md
  - User Guide: 
    - Installation: guide/installation.md
  - Changelog: changelog.md

theme:
  name: terminal
  features:
  - navigation.instant
  - navigation.tracking
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - content.action.edit
  - toc.integrate
  - toc.follow
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.footer

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iteralabs
      name: Follow @iteralabs on GitHub
