[build-system]
requires = ["setuptools", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "atelier"
version = "0.0.3"

[tool.setuptools.packages]
find = { where = ["python"]}

[[tool.setuptools-rust.ext-modules]]
target = "atelier"
path = "Cargo.toml"
binding = "PyO3"
