
[hiper-parameters]
n_past = 30
n_dims = 51
n_future = 10
encoder_units_1 = 200
decoder_units_1 = 200
dropout = 0.4
optimizer = "adam"
batch_size = 64
epochs = 150
learning_rate = 0.0001
cost_function = "MAE"

